trigger:
- main

variables:
  ACR_NAME: suhaso1234
  IMAGE_NAME: flask-s3-app
  IMAGE_TAG: $(Build.SourceVersion)

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: 'acr-registry-cicd'
    repository: $(IMAGE_NAME)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: $(IMAGE_TAG)

- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactName: drop
