apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-file-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-file-manager
  template:
    metadata:
      labels:
        app: s3-file-manager
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: flask-s3-app
        image: suhaso1234.azurecr.io/flask-s3-app:d40af30cc66aeec159da1e6add305233dad5780d
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: aws-secrets
