apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-s3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-s3-app
  template:
    metadata:
      labels:
        app: flask-s3-app
    spec:
      containers:
      - name: flask-s3-container
        image: yourACRName.azurecr.io/flask-s3-app:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 5000
