apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVFEQVJDQ0hGRTVGQUZJVTM=
  AWS_SECRET_ACCESS_KEY: S3JWYXFmcWc4MllLa1pDTTRwZ2Z3N2QzZ2tHODkxY1VEM2FkY3hETw==
  AWS_DEFAULT_REGION: ZXUtbm9ydGgtMQ==
  S3_BUCKET_NAME: c3VoYXM4ODk5
