apiVersion: v1
kind: Service
metadata:
  name: s3-file-manager-service
spec:
  selector:
    app: s3-file-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
